export const products = [
  {
    name: "E.T. Cyber 35000",
    puffs: "35000",
    image: "/products/waka_E.T._cyber_35000.jpeg",
    description: "E.T. Cyber 35000 — футуристический дизайн и 35000 затяжек для тех, кто стремится к новым ощущениям.",
  },
  {
    name: "Burst 41000",
    puffs: "41000",
    image: "/products/waka_burst_41000.jpeg",
    description: "Burst 41000 — всплеск аромата и максимальная автономность для истинных гурманов.",
  },
  {
    name: "Blast 38000",
    puffs: "38000",
    image: "/products/waka_blast_38000.jpeg",
    description: "Blast 38000 — взрывной вкус и рекордная автономность для самых требовательных.",
  },
  {
    name: "xLand Spike 35000",
    puffs: "35000",
    image: "/products/test.png",
    description: "xLand Spike 35000 — экстремальная производительность и уникальный стиль для настоящих лидеров.",
  },
  {
    name: "Jupiter 30000",
    puffs: "30000",
    image: "/products/waka_jupiter_30000.jpeg",
    description: "Jupiter 30000 — космическое количество затяжек и незабываемый вкус в каждой из них.",
  },
  {
    name: "SoPro 20000",
    puffs: "20000",
    image: "/products/waka_soPro_20000.jpeg",
    description: "SoPro 20000 — профессиональная линейка для длительного и стабильного парения.",
  },
  {
    name: "xLand 15000",
    puffs: "15000",
    image: "/products/waka_xLand_15000.jpeg",
    description: "xLand 15000 — дальний путь вкуса и насыщенности для самых требовательных пользователей.",
  },
  {
    name: "SoPro PA10000",
    puffs: "10000",
    image: "/products/waka_soPro_PA10000.jpeg",
    description: "SoPro PA10000 — 10000 затяжек для тех, кто выбирает максимум вкуса и стиля.",
  },
  {
    name: "SoPro 10000",
    puffs: "10000",
    image: "/products/waka_soPro_10000.jpeg",
    description: "SoPro 10000 — 10000 затяжек профессионального вкуса и надёжности.",
  },
  {
    name: "DM 8000i",
    puffs: "8000",
    image: "/products/waka_dm_8000i.jpeg",
    description: "DM 8000i — инновации и 8000 затяжек ярких впечатлений для требовательных пользователей.",
  },
  {
    name: "DM 8000",
    puffs: "8000",
    image: "/products/waka_dm_8000.jpg",
    description: "DM 8000 — современный дизайн и 8000 затяжек для долгого наслаждения любимым вкусом.",
  },
  {
    name: "SoPro PA7000",
    puffs: "7000",
    image: "/products/waka_soPro_PA7000.jpeg",
    description: "SoPro PA7000 — 7000 затяжек насыщенного вкуса и комфорта в каждом вдохе.",
  },
  {
    name: "Smash 6000",
    puffs: "6000",
    image: "/products/waka_smash_6000.jpg",
    description: "Smash на 6000 затяжек — взрывной вкус и максимальное удовольствие в каждой затяжке.",
  },
  {
    name: "soFit FA4500",
    puffs: "4500",
    image: "/products/waka_soFit_FA4500.jpeg",
    description: "SoFit FA4500 — 4500 затяжек чистого вкуса и комфорта для тех, кто ценит качество.",
  },
  {
    name: "Mirror 4500",
    puffs: "4500",
    image: "/products/waka_mirror_4500.jpeg",
    description: "Mirror на 4500 затяжек — отражение баланса аромата и удовольствия в каждом вдохе.",
  },
  {
    name: "Slam 2300",
    puffs: "2300",
    image: "/products/waka_slam_2300.jpg",
    description: "Slam на 2300 затяжек — мощный заряд вкуса и энергии для настоящих ценителей насыщенности.",
  },
  {
    name: "Solo 1800",
    puffs: "1800",
    image: "/products/waka_solo.jpeg",
    description: "Лёгкая и стильная Solo на 1800 затяжек — идеальный спутник для динамичной жизни и ярких вкусовых ощущений.",
  },
]; 